### ISSUE TITLE
KeyError exception using multi_select, options_map_func and OrderedDict

### ISSUE THREAD

**Issue by trunet** [wong2/pick#27]
mydict is a collections.OrderedDict.

```
def get_option(option):
    return f'{getattr(option, "Name")} | {getattr(option, "Hash")}'
title = 'Please choose (press SPACE to mark, ENTER to continue): '
options, index = pick(mydict, title, multi_select=True, min_selection_count=1, options_map_func=get_option)
```

```
Traceback (most recent call last): 
  File "./run.py", line 46, in <module>
    main()
  File "./run.py", line 43, in main
    options, index = pick(mydict, title, multi_select=True, min_selection_count=1, options_map_func=get_option)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pick/__init__.py", line 191, in pick
    return picker.start()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pick/__init__.py", line 177, in start
    return curses.wrapper(self._start)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pick/__init__.py", line 174, in _start
    return self.run_loop()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pick/__init__.py", line 154, in run_loop
    return self.get_selected()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pick/__init__.py", line 76, in get_selected
    return_tuples.append((self.options[selected], selected))
KeyError: 0
```

**Comment by wong2** [comment]
This error means OrderedDict items is not accessible with number index.
Make it clear: `options` must be a list, OrderedDict is not supported
